
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'TransactSdkExample' do
  source 'https://cdn.cocoapods.org/'
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'transact-react-native', :path => '../..'

  pod 'AtomicSDK', :git => 'git@github.com:atomicfi/atomic-transact-ios.git', :branch => 'main'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  # post_install do |installer|
    # flipper_post_install(installer)
  # end
end
