/**
 * Expo config plugin for the Appium test environment.
 *
 * The shared conformance suite (mobile-conformance-tests) drives the native Android test app by:
 *   - starting `com.atomicfi.appiumtestenvironment/.MainActivity` with TRANSACT_* intent extras
 *   - broadcasting to an explicitly-named `.TransactCommandReceiver` component
 *   - matching logcat lines containing `AppiumTestEnvironment`
 *
 * None of that is reachable from JS on its own, and `android/` is regenerated by every prebuild, so
 * this plugin injects the native pieces at prebuild time: a React Native module that reads the
 * launch intent's extras and relays commands, the manifest-declared broadcast receiver the suite
 * addresses by name, and the module's registration in MainApplication.
 */

const {
  AndroidConfig,
  IOSConfig,
  withAndroidManifest,
  withMainApplication,
  withDangerousMod,
  withXcodeProject,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** The package the Kotlin sources are authored under; rewritten to the app's own on copy. */
const SOURCE_PACKAGE = 'com.atomicfi.appiumtestenvironment';
const SOURCE_DIR = path.join(__dirname, 'src', 'android');
const IOS_SOURCE_DIR = path.join(__dirname, 'src', 'ios');
const IOS_SOURCES = ['AppiumHarness.m'];

/**
 * The app's Android applicationId. Everything native is derived from it: manifest-relative class
 * names (`.TransactCommandReceiver`) resolve against it, and the conformance suite builds both the
 * broadcast action and the target component from the same id — so they have to agree.
 */
const androidPackage = (config) => {
  const value = config.android?.package;
  if (!value) {
    throw new Error(
      'withAppiumTestEnvironment: expo.android.package must be set in app.json.'
    );
  }
  // The value is split into directory names when the sources are copied, so reject anything that
  // is not a plain Java package: a stray slash or `..` would write outside the generated project.
  if (!/^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$/.test(value)) {
    throw new Error(
      `withAppiumTestEnvironment: expo.android.package is not a valid Java package name: ${value}`
    );
  }
  return value;
};

/** Copy the Kotlin sources into the generated project, under the harness package. */
const withHarnessSources = (config) =>
  withDangerousMod(config, [
    'android',
    (config) => {
      const pkg = androidPackage(config);
      const destination = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...pkg.split('.')
      );
      fs.mkdirSync(destination, { recursive: true });

      for (const file of fs.readdirSync(SOURCE_DIR)) {
        const source = fs.readFileSync(path.join(SOURCE_DIR, file), 'utf8');
        fs.writeFileSync(
          path.join(destination, file),
          source.replace(`package ${SOURCE_PACKAGE}`, `package ${pkg}`),
          'utf8'
        );
      }

      return config;
    },
  ]);

/**
 * Declare the broadcast receiver. The suite targets it by explicit component
 * (`-n <package>/.TransactCommandReceiver`), which only resolves against a manifest entry — a
 * runtime-registered receiver is not addressable that way.
 */
const withCommandReceiver = (config) =>
  withAndroidManifest(config, (config) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      config.modResults
    );

    application.receiver = (application.receiver || []).filter(
      (item) => item.$?.['android:name'] !== '.TransactCommandReceiver'
    );

    application.receiver.push({
      '$': {
        'android:name': '.TransactCommandReceiver',
        'android:exported': 'true',
      },
      'intent-filter': [
        {
          action: [
            { $: { 'android:name': `${androidPackage(config)}.COMMAND` } },
          ],
        },
      ],
    });

    return config;
  });

/**
 * `singleTask` matches the native test app: relaunching with fresh extras delivers onNewIntent to
 * the existing instance rather than stacking activities.
 */
const withSingleTaskLaunchMode = (config) =>
  withAndroidManifest(config, (config) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(
      config.modResults
    );
    activity.$['android:launchMode'] = 'singleTask';
    return config;
  });

/** Register the harness package with React Native. */
const withPackageRegistration = (config) =>
  withMainApplication(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes('AppiumHarnessPackage()')) {
      return config;
    }

    // The Expo template leaves a commented example inside `PackageList(this).packages.apply { }`
    // for exactly this purpose; append the real registration after it.
    const marker = '// add(MyReactNativePackage())';

    if (!contents.includes(marker)) {
      throw new Error(
        'withAppiumTestEnvironment: could not find the manual package list in MainApplication — the Expo template changed, update this plugin.'
      );
    }

    config.modResults.contents = contents.replace(
      marker,
      `${marker}\n          add(${androidPackage(config)}.AppiumHarnessPackage())`
    );
    return config;
  });

/** Copy the Objective-C module into the generated iOS project, next to the app's own sources. */
const withIosHarnessSources = (config) =>
  withDangerousMod(config, [
    'ios',
    (config) => {
      const projectName = config.modRequest.projectName;
      if (!projectName) {
        throw new Error(
          'withAppiumTestEnvironment: no iOS project name available.'
        );
      }

      const destination = path.join(
        config.modRequest.platformProjectRoot,
        projectName
      );
      fs.mkdirSync(destination, { recursive: true });

      for (const file of IOS_SOURCES) {
        fs.copyFileSync(
          path.join(IOS_SOURCE_DIR, file),
          path.join(destination, file)
        );
      }

      return config;
    },
  ]);

/**
 * Add the module to the app target. Copying the files is not enough — a source file Xcode does not
 * know about is never compiled, and `RCT_EXPORT_MODULE` would never run, leaving
 * `NativeModules.AppiumHarness` undefined at runtime with no build error to explain it.
 */
const withIosBuildSources = (config) =>
  withXcodeProject(config, (config) => {
    const project = config.modResults;
    const projectName = config.modRequest.projectName;

    for (const file of IOS_SOURCES) {
      const filePath = `${projectName}/${file}`;

      if (project.hasFile(filePath)) {
        continue;
      }

      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: filePath,
        groupName: projectName,
        project,
        verbose: false,
      });
    }

    return config;
  });

module.exports = (config) => {
  config = withHarnessSources(config);
  config = withCommandReceiver(config);
  config = withSingleTaskLaunchMode(config);
  config = withPackageRegistration(config);
  config = withIosHarnessSources(config);
  config = withIosBuildSources(config);
  return config;
};
