name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn
      - name: Update package.json version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
          else
            TAG_NAME=$(git describe --tags --abbrev=0)
          fi
          VERSION=${TAG_NAME#v}
          npm version $VERSION --no-git-tag-version
          echo "Updated package.json version to $VERSION"

      - name: Publish
        run: npm publish --access public
