name: Sync Linear Release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - uses: linear/linear-release-action@3f31fcf14c110cc53579fcc3575a26d469c413b4
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY_REACT_NATIVE }}
          command: sync
          timeout: 120
