name: Sync Linear Release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - uses: linear/linear-release-action@af56a9a388625921f3757a2f988e4d7aca958377
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY_REACT_NATIVE }}
          command: sync
          timeout: 120
